version: '3.4'

services:

  db:
    image: "updated_sql_2019"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TipK2iHPR77
    ports:
      - "1440:1433"


  shopifydemoproject:
    image: ${DOCKER_REGISTRY-}shopifydemoproject
    build:
      context: .
      dockerfile: ShopifyDemoProject/Dockerfile
    depends_on:
      - db